# Generated by Django 5.0.4 on 2024-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_cartela_jogador"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartela",
            name="numeros_gerados",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
