# Generated by Django 5.0.4 on 2024-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_cartela_numeros_gerados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="numerosorteado",
            name="cartelas",
        ),
        migrations.RemoveField(
            model_name="numerosorteado",
            name="numero",
        ),
        migrations.AddField(
            model_name="numerosorteado",
            name="numeros",
            field=models.JSONField(null=True),
        ),
    ]
