# Generated by Django 5.0.4 on 2024-05-02 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_numerosorteado_numeros"),
    ]

    operations = [
        migrations.AddField(
            model_name="numerosorteado",
            name="data_hora_sorteio",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
