# Generated by Django 5.0.4 on 2024-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_numerosorteado_data_hora_sorteio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numerosorteado",
            name="numeros",
            field=models.JSONField(default=list),
        ),
    ]
