# Generated by Django 5.0.4 on 2024-05-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_numerosorteado_numeros"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartela",
            name="id_sorteio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartelas_sorteio",
                to="polls.numerosorteado",
            ),
        ),
        migrations.AlterField(
            model_name="cartela",
            name="numeros",
            field=models.ManyToManyField(
                blank=True, related_name="cartelas_numeros", to="polls.numerosorteado"
            ),
        ),
    ]
