# Generated by Django 5.0.4 on 2024-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_cartela_id_sorteio_alter_cartela_numeros"),
    ]

    operations = [
        migrations.AddField(
            model_name="numerosorteado",
            name="cartela_keno",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="numerosorteado",
            name="cartela_kina",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="numerosorteado",
            name="cartela_kuadra",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
